### ISSUE TITLE
save method not work on Android 

### ISSUE THREAD

**Issue by Joseph-Nathan** [incrediblezayed/file_saver#41]
i get that when try save method on Android ,

> D/FileSaver( 5937): Dialog was null
D/FileSaver( 5937): Creating File Dialog Activity
D/FileSaver( 5937): Activity was null
D/FileSaver( 5937): Get directory Method Called
D/FileSaver( 5937): Error While Calling methodnull

**Comment by incrediblezayed** [comment]
Can you share a bit more info, I'll check it out

**Comment by Joseph-Nathan** [comment]
it happened when i used it in background method (FirebaseMessaging.onBackgroundMessage),
which work when app is background or killed ,
i think the solution is providing initialized method to dart package on start (path_provider) ,
if you found fast solution please tell me .

**Comment by incrediblezayed** [comment]
Yeah I will research on it and will let you know

**Comment by OppositeDragon** [comment]
I have exactly the same issue

![image](https://user-images.githubusercontent.com/41167198/184727062-2a7c5c82-f42c-4bf1-acc4-ba056b5749ea.png)
![image](https://user-images.githubusercontent.com/41167198/184727105-7e1f64d4-33ca-4381-b623-7bfe735a62c2.png)

But instead, I try to save a file, created with data from the appilcation, in my case es a 'csv' file.


```dart
...
final bytes = utf8.encode(csvData);
Uint8List bytes8 = Uint8List.fromList(bytes);
FileSaver.instance.saveFile('${report.title}', bytes8, 'csv', mimeType: MimeType.CSV);
...
``` 
I am also trying on linux, and I have a similar issue. The file is not saved, but there is no output on the console either.

**Comment by rshrc** [comment]
@OppositeDragon did you make it work?

**Comment by OppositeDragon** [comment]
> @OppositeDragon did you make it work?

I had to use a different approach, as far as I remember I used another package

**Comment by Myzel394** [comment]
@OppositeDragon do you know what package you used?

**Comment by incrediblezayed** [comment]
Can you help me reproduce the issue?

**Comment by incrediblezayed** [comment]
Okay, I'll try that

**Comment by nikhilmufc7** [comment]
Facing the same issue , it throws `':app:checkDebugDuplicateClasses'.`

**Comment by incrediblezayed** [comment]
Hi guys, please test the latest version, I fixed this issue, if not please reopen it

**Comment by Myzel394** [comment]
@incrediblezayed unfortunately it still does not work for me :/

**Comment by marcuscorreasmash** [comment]
same problem to me in Android. I'll try save csv file and dont is saved. Showed error em debug console just: Get directory Method Called. 

Flutter web works

**Comment by incrediblezayed** [comment]
> @incrediblezayed unfortunately it still does not work for me :/

Please join discord, let's connect there to reproduce

**Comment by sadespresso** [comment]
Hello! I have this exact issue too!

The method doesn't throw error, and print logs only print

```
D/FileSaver(13936): Dialog was null
D/FileSaver(13936): Creating File Dialog Activity
D/FileSaver(13936): Get directory Method Called
```

Please reopen the issue since it is not resolved yet, so other people may find it easier :)

**Comment by incrediblezayed** [comment]
> Hello! I have this exact issue too!
> 
> The method doesn't throw error, and print logs only print
> 
> ```
> D/FileSaver(13936): Dialog was null
> D/FileSaver(13936): Creating File Dialog Activity
> D/FileSaver(13936): Get directory Method Called
> ```
> 
> Please reopen the issue since it is not resolved yet, so other people may find it easier :)

Hello all, can you guys create this bug in discord channel so that we all can follow up on this?

**Comment by Binozo** [comment]
> @incrediblezayed
> 
> Yes, here's what you need to do:
> 
>     1. Create a new Flutter project (tried both stable and beta Flutter channel)
> 
>     2. `flutter pub add file_saver`
> 
>     3. Try running the project
> 
> 
> Here's the error that occurs on startup:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:checkDebugDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
>      Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.5.30 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30)
> 
>      Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
> ```

I get the same error :/

**Comment by Binozo** [comment]
I found the fix. And I show you how you can fix it yourself:

First you need to pair close attention to your error message:
```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations$ReflectSdkVersion found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.jvm.jdk8.JvmRepeatableKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.jvm.optionals.OptionalsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.random.jdk8.PlatformThreadLocalRandom found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.streams.jdk8.StreamsKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$1 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$2 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$3 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.streams.jdk8.StreamsKt$asSequence$$inlined$Sequence$4 found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.text.jdk8.RegexExtensionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)
     Duplicate class kotlin.time.jdk8.DurationConversionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

1. We pick a line that starts with `Duplicate class <module>`
2. Analyse it. What does it tell?
3. `kotlin.jvm.jdk8.JvmRepeatableKt found in modules <module1> and <module2>` tells us that something is duplicated. Maybe the wrong version?
4. Now we look into the modules: `kotlin.jvm.jdk8.JvmRepeatableKt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.21 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21)`
5. We can see that `kotlin-stdlib-jdk8-1.7.21` and `kotlin-stdlib:1.8.0` are conflicting. Kotlin version `1.8.0` vs. `1.7.21`!!
6. Look into your `android/build.gradle`. Right at the top in `buildscript` you will find `ext.kotlin_version = '<YOUR_KOTLIN_VERSION>'`
7. Mine was set to `1.7.21`. So that means that the library uses `1.8.0` and it is conflicting with my project version.
8. Updated mine to `ext.kotlin_version = '1.8.0'`
9. Run `flutter clean` and `flutter pub get`
10. Now you can run your app again 😎
