### ISSUE TITLE
'Save As' does not work on MacOS

### ISSUE THREAD

**Issue by ologunB** [incrediblezayed/file_saver#52]
The `save as` function doesnt work on MacOS, save works fine. Tried digging deeper and realised the 
``` await _channel.invokeMethod<String>(_saveAs, args) ``` in `_openFileManager` doesnt complete or return any value. Cant go any deeper as I do not write swift. 

MacOS, Monterey, version 12.6

Weldone on such a great package though, really helpful.

**Comment by incrediblezayed** [comment]
It is resolved in the latest version please check, reopen the issue if not

**Comment by arianshi** [comment]
Hi,  when I used the version 0.2.0. it is still not working.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/122079456/233890792-7700dccf-9449-49bd-9df6-6b8f6b2a1cbe.png">

**Comment by arianshi** [comment]
Hi @incrediblezayed 
  Thank for you updating. It is working now.

**Comment by programmeraditya** [comment]
This doesn't work for me still. I am using version 0.2.6. The **saveAs** method doesn't return anything, so the future never completes. I am on MacOS Ventura 13.0 (M1 Chip). Flutter version is 3.7.5. The **saveFile** method works fine though. The reason I wanted to use saveAs was the saveFile method was not overwriting the file if it had the same name.

**Comment by incrediblezayed** [comment]
> This doesn't work for me still. I am using version 0.2.6. The **saveAs** method doesn't return anything, so the future never completes. I am on MacOS Ventura 13.0 (M1 Chip). Flutter version is 3.7.5. The **saveFile** method works fine though. The reason I wanted to use saveAs was the saveFile method was not overwriting the file if it had the same name.

I really can't reproduce this, since I've already tested this multiple times, have you added the required entitlements in DebugProfile.entitlements?

**Comment by programmeraditya** [comment]
<img width="862" alt="Screenshot 2023-08-06 at 1 57 23 AM" src="https://github.com/incrediblezayed/file_saver/assets/24489590/22695c76-2697-45e5-b7a4-8943a5cd7a47">
Yes, it's there. I double checked everything, but still couldn't get it to work. 

`await FileSaver.instance.saveAs(name: fileName, bytes: Uint8List.fromList(export.codeUnits), ext: 'csv', mimeType: MimeType.csv);`

This is the code.

**Comment by incrediblezayed** [comment]
> <img width="862" alt="Screenshot 2023-08-06 at 1 57 23 AM" src="https://github.com/incrediblezayed/file_saver/assets/24489590/22695c76-2697-45e5-b7a4-8943a5cd7a47">
> Yes, it's there. I double checked everything, but still couldn't get it to work. 
> 
> `await FileSaver.instance.saveAs(name: fileName, bytes: Uint8List.fromList(export.codeUnits), ext: 'csv', mimeType: MimeType.csv);`
> 
> This is the code.

I actually have the exact same macbook as you, but I never faced this, I'll try this tomorrow morning, can you join discord if possible?

**Comment by programmeraditya** [comment]
I figured out what was happening. As you can see from the screenshot in my previous reply, I have [App Sandbox](https://developer.apple.com/documentation/security/app_sandbox) enabled as it's a requirement to publish to App Store. So, I had to also add com.apple.security.files.user-selected.read-write key in entitlements file as App Sandbox disables it by default. When a Save As dialog appears, it no longer becomes a Downloads folder access, but a 'User Selected' one, so that's why. 

`<key>com.apple.security.files.user-selected.read-write</key>
	<true/>`

<img width="781" alt="Screenshot 2023-08-06 at 2 15 08 AM" src="https://github.com/incrediblezayed/file_saver/assets/24489590/ed9c079e-d562-4247-8954-d4810344cfe0">

**Comment by incrediblezayed** [comment]
> I figured out what was happening. As you can see from the screenshot in my previous reply, I have [App Sandbox](https://developer.apple.com/documentation/security/app_sandbox) enabled as it's a requirement to publish to App Store. So, I had to also add com.apple.security.files.user-selected.read-write key in entitlements file as App Sandbox disables it by default. When a Save As dialog appears, it no longer becomes a Downloads folder access, but a 'User Selected' one, so that's why. 
> 
> `<key>com.apple.security.files.user-selected.read-write</key>
> 	<true/>`
> 
> <img width="781" alt="Screenshot 2023-08-06 at 2 15 08 AM" src="https://github.com/incrediblezayed/file_saver/assets/24489590/ed9c079e-d562-4247-8954-d4810344cfe0">
> 

Is it fixed now?

**Comment by programmeraditya** [comment]
Yes, working fine after adding `com.apple.security.files.user-selected.read-write` key to the entitlements file. Thanks!

**Comment by incrediblezayed** [comment]
So closing the issue

**Comment by T-P-F** [comment]
Should probably update the readme with this info [here](https://pub.dev/packages/file_saver#macos)

Just encountered this issue and this was the fix ^^
