### ISSUE TITLE
UnimplementedError (UnimplementedError: Unimplemented Error)

### ISSUE THREAD

**Issue by milindgoel15** [incrediblezayed/file_saver#80]
It seems the Windows implementation is not done. Trying to save a file from the Windows app and it keeps throwing an unimplemented error. I saw a PR related to windows support https://github.com/incrediblezayed/file_saver/pull/72. Maybe that will solve anything

**Comment by incrediblezayed** [comment]
Hey, yes, that might solve the issue, will try to merge that asap

**Comment by incrediblezayed** [comment]
Hey @milindgoel15 I just merged the PR can you help me test on windows? I don't have a windows machine..

**Comment by milindgoel15** [comment]
Just tested out all three save modes (saveAs, saveFile, saveFileOnly) and they work as expected. The saveAs function works in the way described in the PR.

**Comment by milindgoel15** [comment]
Believe this could be closed as it was merged.

If issue persists tho, will reopen or something.
